### ISSUE TITLE
incorrect repository name

### ISSUE THREAD

**Issue by danmarsden** [jmulet/moodle-tiny_codepro#1]
Your repository name should ideally use the standard frankenstyle Moodle naming convention which makes it easy for moodle admins to identify your plugin.

the correct format to use is moodle-{frankenstylepluginname}
eg if your plugin was "tiny_codepro" the correct name to use would be: "moodle-tiny_codepro"

Github maintains redirects from your old name to the new one which makes this very easy - just hit the "settings" tab on your github repository and the rename repository option should appear near the top. 

Not a blocker for plugins db approval, just a nice convention to follow if possible.

**Comment by jmulet** [comment]
Hi Dan,
Thank you very much for the comment.
The repository has been renamed to moodle-tiny_codepro
