### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dinism** [jmulet/moodle-tiny_codepro#15]
I'm PT-PT translator.

Thanks a lot for the plugin.

Can the mouse over button message be translated?

The strings are:
Fullscreen
Light/Dark themes
Line wrap
Prettify code
Auto prettify when editors open

TIA

**Comment by jmulet** [comment]
Hi @dinism,
Yes. The translation is possible for those strings. I'll do the changes for the next release.

**Comment by jmulet** [comment]
Hi,
I have just made a commit to the develop branch with the changes.
https://github.com/jmulet/moodle-tiny_codepro/commit/058263a16fb3329a4a9ba3abf2092e6cdfe7fcac

The new strings for the tooltips are

$string['autoprettify'] = 'Auto prettify when editor opens';
$string['fullscreen'] = 'Fullscreen';
$string['linewrap'] = 'Line wrap';
$string['prettify'] = 'Prettify code';
$string['themes'] = 'Light/Dark themes';

**Comment by jmulet** [comment]
The new version 1.1.4 has been released at
[https://moodle.org/plugins/tiny_codepro/1.1.4/34079](https://moodle.org/plugins/tiny_codepro/1.1.4/34079)
which addresses the current issue.
Closing.
