### ISSUE TITLE
Sourcecode pro auto convert span tag html to p tag

### ISSUE THREAD

**Issue by tailetan** [jmulet/moodle-tiny_codepro#17]
Currently, Sourcecode Pro automatically converts the <span> HTML tag to a <p> tag. Please refer to the attachment below:

https://github.com/user-attachments/assets/d2e28560-2f86-43bf-bf02-173b3958d592

**Expected Behavior:** Sourcecode Pro should retain the <span> tag and not convert it to a <p> tag.

FYI: @jmulet

**Comment by jmulet** [comment]
Hi @tailetan ,
I am afraid that this is related to the internal behavior of the Tiny editor and has nothing to do with my plugin.
Please look at this Tiny documentation page
https://www.tiny.cloud/docs/tinymce/latest/content-filtering/#:~:text=%3A%20true%0A%7D)%3B-,forced_root_block,-This%20option%20enables
