### ISSUE TITLE
consider adding github actions support (it's free and very useful)

### ISSUE THREAD

**Issue by danmarsden** [jmulet/moodle-tiny_codepro#2]
Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/MOODLE_311_STABLE/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by jmulet** [comment]
Hi Dan,

I have added the moodle-plugin-ci in the workflow.  It has been very useful tool to fix some lint issues.
However, I am unable to solve an error that appears after the grunt amd task.
It says that two files are stale and needs to be rebuilt. Any clue?

<img width="883" alt="Captura de pantalla 2024-01-19 a les 15 27 02" src="https://github.com/jmulet/moodle-tiny_codepro/assets/5049732/08f8a401-b609-4027-a925-5eed7efae6f2">

**Comment by danmarsden** [comment]
you don't have to fix all those issues for approval in the plugins db, - that error usually means something has gone wrong when you've run grunt locally and you haven't committed the updated versions of all files - there's more docs here:
https://moodledev.io/general/development/tools/nodejs

But you could also try asking for help in the community forums if you're still stuck.
